### ISSUE TITLE
Opdatering af filerne?

### ISSUE THREAD

**Issue by henrikkorsgaard** [Neogeografen/dagi#3]
Hej Søren,

Ville det være muligt om du kunne opdatere geo-/topoJSON filerne i dette repo? Der er sket et par ting de sidste år med sammenlægning af fx sogne. 

(Alternativt: pege mig i retning af hvor jeg selv kan hente dem i mere opdateret format)

På forhånd tak!

**Comment by Neogeografen** [comment]
Hej Henrik

Mine filerne blev lavet den gang det offentlige ikke tilbød gratis geodata
, men det gør de nu. Du skal hen på Dataforsyningen og oprettte en konto
https://dataforsyningen.dk/

samt oprette en token og så skal du have fat i dette her datasæt
https://dataforsyningen.dk/data/3559

Bemærk der er i flere opløsninger 1:500000 og 1:250000 og formater du skal
vælge WFS så får du det som vektordata - Den WFS URL du får kan du åbne i
det open source QGIS program og så kan du eksporte til andet format fx
GeoJSON eller skyde ind i PostgreSQL/PostGIS via QGIS datamanager.

Med venlig hilsen
Søren Johannessen
